# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16e6ddd22762179bc614d632c55886762c37a1d461585baa34e3bab86d4c7cf5e2aea020779a71b59cedb7c8477cf13cdf003f53d4909c14e595137677bd4296

test:
  secret_key_base: 77069aa4b6e10615a445c31edad76c4401f95b98b89bee2c02dbd1d609e6068a566287c382626d00f5c40ac25094c9d3a9097d2e89a5e6ed40e4a074a41b891a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
